# Generated by Django 5.1.4 on 2025-01-05 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpstore',
            name='id',
        ),
        migrations.AlterField(
            model_name='otpstore',
            name='email',
            field=models.EmailField(max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.EmailValidator]),
        ),
    ]
