# Generated by Django 5.1.4 on 2025-01-05 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_remove_otpstore_id_alter_otpstore_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPStore1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, validators=[django.core.validators.EmailValidator])),
                ('otp', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6)])),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
