# Generated by Django 5.1.4 on 2025-01-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_otpstore1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPStore',
        ),
    ]
