# Generated by Django 5.1.4 on 2025-01-05 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_delete_otpstore'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OTPStore1',
            new_name='OTPStore',
        ),
    ]
